name: soycraft-crafting-additions
version: 1.0
main: com.recipe.recipes
api-version: 1.13
authors: [baritone]
description: Adds additional crafting recipes to improve late-game crafting and automation

